/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/PtFlob.def

namespace KBEngine
{

class KBENGINEPLUGINS_API EntityBaseEntityCall_PtFlobBase : public EntityCall
{
public:

	EntityBaseEntityCall_PtFlobBase(int32 eid, const FString& ename);

	virtual ~EntityBaseEntityCall_PtFlobBase();
};

class KBENGINEPLUGINS_API EntityCellEntityCall_PtFlobBase : public EntityCall
{
public:

	EntityCellEntityCall_PtFlobBase(int32 eid, const FString& ename);

	virtual ~EntityCellEntityCall_PtFlobBase();
};

}