/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/PtAccount.def

namespace KBEngine
{

class KBENGINEPLUGINS_API EntityBaseEntityCall_PtAccountBase : public EntityCall
{
public:

	EntityBaseEntityCall_PtAccountBase(int32 eid, const FString& ename);

	virtual ~EntityBaseEntityCall_PtAccountBase();
};

class KBENGINEPLUGINS_API EntityCellEntityCall_PtAccountBase : public EntityCall
{
public:

	EntityCellEntityCall_PtAccountBase(int32 eid, const FString& ename);

	virtual ~EntityCellEntityCall_PtAccountBase();
};

}