/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/PtSkill.def

namespace KBEngine
{

class KBENGINEPLUGINS_API EntityBaseEntityCall_PtSkillBase : public EntityCall
{
public:

	EntityBaseEntityCall_PtSkillBase(int32 eid, const FString& ename);

	virtual ~EntityBaseEntityCall_PtSkillBase();
};

class KBENGINEPLUGINS_API EntityCellEntityCall_PtSkillBase : public EntityCall
{
public:

	EntityCellEntityCall_PtSkillBase(int32 eid, const FString& ename);

	virtual ~EntityCellEntityCall_PtSkillBase();
};

}