/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/PtRoom.def

namespace KBEngine
{

class KBENGINEPLUGINS_API EntityBaseEntityCall_PtRoomBase : public EntityCall
{
public:

	EntityBaseEntityCall_PtRoomBase(int32 eid, const FString& ename);

	virtual ~EntityBaseEntityCall_PtRoomBase();
};

class KBENGINEPLUGINS_API EntityCellEntityCall_PtRoomBase : public EntityCall
{
public:

	EntityCellEntityCall_PtRoomBase(int32 eid, const FString& ename);

	virtual ~EntityCellEntityCall_PtRoomBase();
};

}