/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/PtRole.def

namespace KBEngine
{

class KBENGINEPLUGINS_API EntityBaseEntityCall_PtRoleBase : public EntityCall
{
public:

	EntityBaseEntityCall_PtRoleBase(int32 eid, const FString& ename);

	virtual ~EntityBaseEntityCall_PtRoleBase();
};

class KBENGINEPLUGINS_API EntityCellEntityCall_PtRoleBase : public EntityCall
{
public:

	EntityCellEntityCall_PtRoleBase(int32 eid, const FString& ename);

	virtual ~EntityCellEntityCall_PtRoleBase();
};

}