/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/PtAccount.def

namespace KBEngine
{

class KBENGINEPLUGINS_API EntityBaseEntityCall_PtAccountBase : public EntityCall
{
public:

	EntityBaseEntityCall_PtAccountBase(int32 eid, const FString& ename);

	virtual ~EntityBaseEntityCall_PtAccountBase();
	void ReqCreateRole(uint8 arg1, const FString& arg2);
	void ReqCreateRoom(const FString& arg1);
	void ReqRemoveRole(const FString& arg1);
	void ReqRoleList();
	void ReqRoomList();
	void ReqSelectRoleGame(uint64 arg1);
	void SelectRoomGame(uint64 arg1);
};

class KBENGINEPLUGINS_API EntityCellEntityCall_PtAccountBase : public EntityCall
{
public:

	EntityCellEntityCall_PtAccountBase(int32 eid, const FString& ename);

	virtual ~EntityCellEntityCall_PtAccountBase();
};

}