/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class PtAccount : public PtAccountBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "EntityCallPtAccountBase.h"

namespace KBEngine
{

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/PtAccount.def
	// Please inherit and implement "class PtAccount : public PtAccountBase"
class KBENGINEPLUGINS_API PtAccountBase : public Entity
{
public:
	EntityBaseEntityCall_PtAccountBase* pBaseEntityCall;
	EntityCellEntityCall_PtAccountBase* pCellEntityCall;

	uint64 LastSelRole;
	virtual void onLastSelRoleChanged(uint64 oldValue) {}

	virtual void OnCreateRoleResult(uint8 arg1, const ROLE_INFO& arg2) = 0; 
	virtual void OnRemoveRole(uint64 arg1) = 0; 
	virtual void OnReqRoleList(const ROLE_LIST& arg1) = 0; 
	virtual void OnSelectRoleGame(uint8 arg1, uint64 arg2) = 0; 

	void onComponentsEnterworld() override;
	void onComponentsLeaveworld() override;

	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;


	void onRemoteMethodCall(MemoryStream& stream) override;
	void onUpdatePropertys(MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	PtAccountBase();
	virtual ~PtAccountBase();

	void attachComponents() override;
	void detachComponents() override;

};

}