/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class PtFlob : public PtFlobBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "EntityCallPtFlobBase.h"

namespace KBEngine
{

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/PtFlob.def
	// Please inherit and implement "class PtFlob : public PtFlobBase"
class KBENGINEPLUGINS_API PtFlobBase : public Entity
{
public:
	EntityBaseEntityCall_PtFlobBase* pBaseEntityCall;
	EntityCellEntityCall_PtFlobBase* pCellEntityCall;

	uint8 GoodId;
	virtual void onGoodIdChanged(uint8 oldValue) {}


	void onComponentsEnterworld() override;
	void onComponentsLeaveworld() override;

	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;


	void onRemoteMethodCall(MemoryStream& stream) override;
	void onUpdatePropertys(MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	PtFlobBase();
	virtual ~PtFlobBase();

	void attachComponents() override;
	void detachComponents() override;

};

}