/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class PtRoomMgr : public PtRoomMgrBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "EntityCallPtRoomMgrBase.h"

namespace KBEngine
{

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/PtRoomMgr.def
	// Please inherit and implement "class PtRoomMgr : public PtRoomMgrBase"
class KBENGINEPLUGINS_API PtRoomMgrBase : public Entity
{
public:
	EntityBaseEntityCall_PtRoomMgrBase* pBaseEntityCall;
	EntityCellEntityCall_PtRoomMgrBase* pCellEntityCall;



	void onComponentsEnterworld() override;
	void onComponentsLeaveworld() override;

	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;


	void onRemoteMethodCall(MemoryStream& stream) override;
	void onUpdatePropertys(MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	PtRoomMgrBase();
	virtual ~PtRoomMgrBase();

	void attachComponents() override;
	void detachComponents() override;

};

}