/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class PtRoom : public PtRoomBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "EntityCallPtRoomBase.h"

namespace KBEngine
{

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/PtRoom.def
	// Please inherit and implement "class PtRoom : public PtRoomBase"
class KBENGINEPLUGINS_API PtRoomBase : public Entity
{
public:
	EntityBaseEntityCall_PtRoomBase* pBaseEntityCall;
	EntityCellEntityCall_PtRoomBase* pCellEntityCall;



	void onComponentsEnterworld() override;
	void onComponentsLeaveworld() override;

	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;


	void onRemoteMethodCall(MemoryStream& stream) override;
	void onUpdatePropertys(MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	PtRoomBase();
	virtual ~PtRoomBase();

	void attachComponents() override;
	void detachComponents() override;

};

}