/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class PtSkill : public PtSkillBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "EntityCallPtSkillBase.h"

namespace KBEngine
{

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/PtSkill.def
	// Please inherit and implement "class PtSkill : public PtSkillBase"
class KBENGINEPLUGINS_API PtSkillBase : public Entity
{
public:
	EntityBaseEntityCall_PtSkillBase* pBaseEntityCall;
	EntityCellEntityCall_PtSkillBase* pCellEntityCall;

	uint8 SkillId;
	virtual void onSkillIdChanged(uint8 oldValue) {}


	void onComponentsEnterworld() override;
	void onComponentsLeaveworld() override;

	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;


	void onRemoteMethodCall(MemoryStream& stream) override;
	void onUpdatePropertys(MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	PtSkillBase();
	virtual ~PtSkillBase();

	void attachComponents() override;
	void detachComponents() override;

};

}